### PR TITLE
Selinux boolean, mysql travis check

### PR DESCRIPTION
**Pull request by abelboldu**

### CODE REVIEW

**Comment by ryo-tagami** [comment]
👀

**Review by ryo-tagami — COMMENTED** [review]
Idempotency check failed on CentOS. Probably service is failing to start up correctly?

```
11:32:00 changed: [localhost] => (item=neutron-linuxbridge-agent) => {"changed": true, "enabled": true, "item": "neutron-linuxbridge-agent", "name": "neutron-linuxbridge-agent", "state": "started", "status": {"ActiveEnterTimestamp": "Wed 2017-03-01 10:29:52 UTC", "ActiveEnterTimestampMonotonic": "923755977", "ActiveExitTimestamp": "Wed 2017-03-01 10:29:54 UTC", "ActiveExitTimestampMonotonic": "925274668", "ActiveState": "failed", "After": "syslog.target network.target systemd-journald.socket basic.target -.mount system.slice tmp.mount", "AllowIsolate": "no", "AssertResult": "yes", "AssertTimestamp": "Wed 2017-03-01 10:29:52 UTC", "AssertTimestampMonotonic": "923730145", "Before": "shutdown.target multi-user.target", "BlockIOAccounting": "no", "BlockIOWeight": "18446744073709551615", "CPUAccounting": "no", "CPUQuotaPerSecUSec": "infinity", "CPUSchedulingPolicy": "0", "CPUSchedulingPriority": "0", "CPUSchedulingResetOnFork": "no", "CPUShares": "18446744073709551615", "CanIsolate": "no", "CanReload": "no", "CanStart": "yes", "CanStop": "yes", "CapabilityBoundingSet": "18446744073709551615", "ConditionResult": "yes", "ConditionTimestamp": "Wed 2017-03-01 10:29:52 UTC", "ConditionTimestampMonotonic": "923730144", "Conflicts": "shutdown.target", "ControlPID": "0", "DefaultDependencies": "yes", "Delegate": "no", "Description": "OpenStack Neutron Linux Bridge Agent", "DevicePolicy": "auto", "ExecMainCode": "1", "ExecMainExitTimestamp": "Wed 2017-03-01 10:29:54 UTC", "ExecMainExitTimestampMonotonic": "925274080", "ExecMainPID": "15685", "ExecMainStartTimestamp": "Wed 2017-03-01 10:29:52 UTC", "ExecMainStartTimestampMonotonic": "923755904", "ExecMainStatus": "1", "ExecStart": "{ path=/usr/bin/neutron-linuxbridge-agent ; argv[]=/usr/bin/neutron-linuxbridge-agent --config-file /usr/share/neutron/neutron-dist.conf --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/linuxbridge_agent.ini --config-dir /etc/neutron/conf.d/common --config-dir /etc/neutron/conf.d/neutron-linuxbridge-agent --log-file /var/log/neutron/linuxbridge-agent.log ; ignore_errors=no ; start_time=[Wed 2017-03-01 10:29:52 UTC] ; stop_time=[Wed 2017-03-01 10:29:54 UTC] ; pid=15685 ; code=exited ; status=1 }", "ExecStartPre": "{ path=/usr/bin/neutron-enable-bridge-firewall.sh ; argv[]=/usr/bin/neutron-enable-bridge-firewall.sh ; ignore_errors=no ; start_time=[Wed 2017-03-01 10:29:52 UTC] ; stop_time=[Wed 2017-03-01 10:29:52 UTC] ; pid=15678 ; code=exited ; status=0 }", "FailureAction": "none", "FileDescriptorStoreMax": "0", "FragmentPath": "/usr/lib/systemd/system/neutron-linuxbridge-agent.service", "GuessMainPID": "yes", "IOScheduling": "0", "Id": "neutron-linuxbridge-agent.service", "IgnoreOnIsolate": "no", "IgnoreOnSnapshot": "no", "IgnoreSIGPIPE": "yes", "InactiveEnterTimestamp": "Wed 2017-03-01 10:29:54 UTC", "InactiveEnterTimestampMonotonic": "925274668", "InactiveExitTimestamp": "Wed 2017-03-01 10:29:52 UTC", "InactiveExitTimestampMonotonic": "923731329", "JobTimeoutAction": "none", "JobTimeoutUSec": "0", "KillMode": "process", "KillSignal": "15", "LimitAS": "18446744073709551615", "LimitCORE": "18446744073709551615", "LimitCPU": "18446744073709551615", "LimitDATA": "18446744073709551615", "LimitFSIZE": "18446744073709551615", "LimitLOCKS": "18446744073709551615", "LimitMEMLOCK": "65536", "LimitMSGQUEUE": "819200", "LimitNICE": "0", "LimitNOFILE": "4096", "LimitNPROC": "31147", "LimitRSS": "18446744073709551615", "LimitRTPRIO": "0", "LimitRTTIME": "18446744073709551615", "LimitSIGPENDING": "31147", "LimitSTACK": "18446744073709551615", "LoadState": "loaded", "MainPID": "0", "MemoryAccounting": "no", "MemoryCurrent": "18446744073709551615", "MemoryLimit": "18446744073709551615", "MountFlags": "0", "Names": "neutron-linuxbridge-agent.service", "NeedDaemonReload": "no", "Nice": "0", "NoNewPrivileges": "no", "NonBlocking": "no", "NotifyAccess": "none", "OOMScoreAdjust": "0", "OnFailureJobMode": "replace", "PermissionsStartOnly": "yes", "PrivateDevices": "no", "PrivateNetwork": "no", "PrivateTmp": "yes", "ProtectHome": "no", "ProtectSystem": "no", "RefuseManualStart": "no", "RefuseManualStop": "no", "RemainAfterExit": "no", "Requires": "-.mount basic.target", "RequiresMountsFor": "/var/tmp", "Restart": "no", "RestartUSec": "100ms", "Result": "exit-code", "RootDirectoryStartOnly": "no", "RuntimeDirectoryMode": "0755", "SameProcessGroup": "no", "SecureBits": "0", "SendSIGHUP": "no", "SendSIGKILL": "yes", "Slice": "system.slice", "StandardError": "inherit", "StandardInput": "null", "StandardOutput": "journal", "StartLimitAction": "none", "StartLimitBurst": "5", "StartLimitInterval": "10000000", "StartupBlockIOWeight": "18446744073709551615", "StartupCPUShares": "18446744073709551615", "StatusErrno": "0", "StopWhenUnneeded": "no", "SubState": "failed", "SyslogLevelPrefix": "yes", "SyslogPriority": "30", "SystemCallErrorNumber": "0", "TTYReset": "no", "TTYVHangup": "no", "TTYVTDisallocate": "no", "TimeoutStartUSec": "1min 30s", "TimeoutStopUSec": "1min 30s", "TimerSlackNSec": "50000", "Transient": "no", "Type": "simple", "UMask": "0022", "UnitFilePreset": "disabled", "UnitFileState": "enabled", "User": "neutron", "WantedBy": "multi-user.target", "Wants": "system.slice", "WatchdogTimestampMonotonic": "0", "WatchdogUSec": "0"}, "warnings": []}
```

**Comment by abelboldu** [comment]
will check on vagrant later

On 1 March 2017 12:51:23 CET, Ryo Tagami <notifications@github.com> wrote:
>ryo-tagami commented on this pull request.
>
>Idempotency check failed on CentOS. Probably service is failing to
>start up correctly?
>
>```
>11:32:00 changed: [localhost] => (item=neutron-linuxbridge-agent) =>
>{"changed": true, "enabled": true, "item": "neutron-linuxbridge-agent",
>"name": "neutron-linuxbridge-agent", "state": "started", "status":
>{"ActiveEnterTimestamp": "Wed 2017-03-01 10:29:52 UTC",
>"ActiveEnterTimestampMonotonic": "923755977", "ActiveExitTimestamp":
>"Wed 2017-03-01 10:29:54 UTC", "ActiveExitTimestampMonotonic":
>"925274668", "ActiveState": "failed", "After": "syslog.target
>network.target systemd-journald.socket basic.target -.mount
>system.slice tmp.mount", "AllowIsolate": "no", "AssertResult": "yes",
>"AssertTimestamp": "Wed 2017-03-01 10:29:52 UTC",
>"AssertTimestampMonotonic": "923730145", "Before": "shutdown.target
>multi-user.target", "BlockIOAccounting": "no", "BlockIOWeight":
>"18446744073709551615", "CPUAccounting": "no", "CPUQuotaPerSecUSec":
>"infinity", "CPUSchedulingPolicy": "0", "CPUSchedulingPriority": "0",
>"CPUSchedulingResetOnFork": "no", "CPUShares": "18446744073709551615",
>"CanIsolate": "no", "CanReload": "no", "CanStart": "yes", "CanStop":
>"yes", "CapabilityBoundingSet": "18446744073709551615",
>"ConditionResult": "yes", "ConditionTimestamp": "Wed 2017-03-01
>10:29:52 UTC", "ConditionTimestampMonotonic": "923730144", "Conflicts":
>"shutdown.target", "ControlPID": "0", "DefaultDependencies": "yes",
>"Delegate": "no", "Description": "OpenStack Neutron Linux Bridge
>Agent", "DevicePolicy": "auto", "ExecMainCode": "1",
>"ExecMainExitTimestamp": "Wed 2017-03-01 10:29:54 UTC",
>"ExecMainExitTimestampMonotonic": "925274080", "ExecMainPID": "15685",
>"ExecMainStartTimestamp": "Wed 2017-03-01 10:29:52 UTC",
>"ExecMainStartTimestampMonotonic": "923755904", "ExecMainStatus": "1",
>"ExecStart": "{ path=/usr/bin/neutron-linuxbridge-agent ;
>argv[]=/usr/bin/neutron-linuxbridge-agent --config-file
>/usr/share/neutron/neutron-dist.conf --config-file
>/etc/neutron/neutron.conf --config-file
>/etc/neutron/plugins/ml2/linuxbridge_agent.ini --config-dir
>/etc/neutron/conf.d/common --config-dir
>/etc/neutron/conf.d/neutron-linuxbridge-agent --log-file
>/var/log/neutron/linuxbridge-agent.log ; ignore_errors=no ;
>start_time=[Wed 2017-03-01 10:29:52 UTC] ; stop_time=[Wed 2017-03-01
>10:29:54 UTC] ; pid=15685 ; code=exited ; status=1 }", "ExecStartPre":
>"{ path=/usr/bin/neutron-enable-bridge-firewall.sh ;
>argv[]=/usr/bin/neutron-enable-bridge-firewall.sh ; ignore_errors=no ;
>start_time=[Wed 2017-03-01 10:29:52 UTC] ; stop_time=[Wed 2017-03-01
>10:29:52 UTC] ; pid=15678 ; code=exited ; status=0 }", "FailureAction":
>"none", "FileDescriptorStoreMax": "0", "FragmentPath":
>"/usr/lib/systemd/system/neutron-linuxbridge-agent.service",
>"GuessMainPID": "yes", "IOScheduling": "0", "Id":
>"neutron-linuxbridge-agent.service", "IgnoreOnIsolate": "no",
>"IgnoreOnSnapshot": "no", "IgnoreSIGPIPE": "yes",
>"InactiveEnterTimestamp": "Wed 2017-03-01 10:29:54 UTC",
>"InactiveEnterTimestampMonotonic": "925274668",
>"InactiveExitTimestamp": "Wed 2017-03-01 10:29:52 UTC",
>"InactiveExitTimestampMonotonic": "923731329", "JobTimeoutAction":
>"none", "JobTimeoutUSec": "0", "KillMode": "process", "KillSignal":
>"15", "LimitAS": "18446744073709551615", "LimitCORE":
>"18446744073709551615", "LimitCPU": "18446744073709551615",
>"LimitDATA": "18446744073709551615", "LimitFSIZE":
>"18446744073709551615", "LimitLOCKS": "18446744073709551615",
>"LimitMEMLOCK": "65536", "LimitMSGQUEUE": "819200", "LimitNICE": "0",
>"LimitNOFILE": "4096", "LimitNPROC": "31147", "LimitRSS":
>"18446744073709551615", "LimitRTPRIO": "0", "LimitRTTIME":
>"18446744073709551615", "LimitSIGPENDING": "31147", "LimitSTACK":
>"18446744073709551615", "LoadState": "loaded", "MainPID": "0",
>"MemoryAccounting": "no", "MemoryCurrent": "18446744073709551615",
>"MemoryLimit": "18446744073709551615", "MountFlags": "0", "Names":
>"neutron-linuxbridge-agent.service", "NeedDaemonReload": "no", "Nice":
>"0", "NoNewPrivileges": "no", "NonBlocking": "no", "NotifyAccess":
>"none", "OOMScoreAdjust": "0", "OnFailureJobMode": "replace",
>"PermissionsStartOnly": "yes", "PrivateDevices": "no",
>"PrivateNetwork": "no", "PrivateTmp": "yes", "ProtectHome": "no",
>"ProtectSystem": "no", "RefuseManualStart": "no", "RefuseManualStop":
>"no", "RemainAfterExit": "no", "Requires": "-.mount basic.target",
>"RequiresMountsFor": "/var/tmp", "Restart": "no", "RestartUSec":
>"100ms", "Result": "exit-code", "RootDirectoryStartOnly": "no",
>"RuntimeDirectoryMode": "0755", "SameProcessGroup": "no", "SecureBits":
>"0", "SendSIGHUP": "no", "SendSIGKILL": "yes", "Slice": "system.slice",
>"StandardError": "inherit", "StandardInput": "null", "StandardOutput":
>"journal", "StartLimitAction": "none", "StartLimitBurst": "5",
>"StartLimitInterval": "10000000", "StartupBlockIOWeight":
>"18446744073709551615", "StartupCPUShares": "18446744073709551615",
>"StatusErrno": "0", "StopWhenUnneeded": "no", "SubState": "failed",
>"SyslogLevelPrefix": "yes", "SyslogPriority": "30",
>"SystemCallErrorNumber": "0", "TTYReset": "no", "TTYVHangup": "no",
>"TTYVTDisallocate": "no", "TimeoutStartUSec": "1min 30s",
>"TimeoutStopUSec": "1min 30s", "TimerSlackNSec": "50000", "Transient":
>"no", "Type": "simple", "UMask": "0022", "UnitFilePreset": "disabled",
>"UnitFileState": "enabled", "User": "neutron", "WantedBy":
>"multi-user.target", "Wants": "system.slice",
>"WatchdogTimestampMonotonic": "0", "WatchdogUSec": "0"}, "warnings":
>[]}
>```
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openstack-ansible-galaxy/openstack-neutron-controller/pull/21#pullrequestreview-24459618

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by abelboldu** [comment]
Selinux again
```
[root@allinone-aomi ~]# systemctl status neutron-linuxbridge-agent
● neutron-linuxbridge-agent.service - OpenStack Neutron Linux Bridge Agent
   Loaded: loaded (/usr/lib/systemd/system/neutron-linuxbridge-agent.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2017-03-01 16:24:07 UTC; 9min ago
  Process: 15864 ExecStart=/usr/bin/neutron-linuxbridge-agent --config-file /usr/share/neutron/neutron-dist.conf --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/linuxbridge_agent.ini --config-dir /etc/neutron/conf.d/common --config-dir /etc/neutron/conf.d/neutron-linuxbridge-agent --log-file /var/log/neutron/linuxbridge-agent.log (code=exited, status=1/FAILURE)
  Process: 15857 ExecStartPre=/usr/bin/neutron-enable-bridge-firewall.sh (code=exited, status=0/SUCCESS)
 Main PID: 15864 (code=exited, status=1/FAILURE)

Mar 01 16:24:05 allinone-aomi neutron-enable-bridge-firewall.sh[15857]: net.bridge.bridge-nf-call-iptables = 1
Mar 01 16:24:05 allinone-aomi neutron-enable-bridge-firewall.sh[15857]: net.bridge.bridge-nf-call-ip6tables = 1
Mar 01 16:24:05 allinone-aomi systemd[1]: Started OpenStack Neutron Linux Bridge Agent.
Mar 01 16:24:05 allinone-aomi neutron-linuxbridge-agent[15864]: Guru mediation now registers SIGUSR1 and SIGUSR2 by default for backward c...ports.
Mar 01 16:24:06 allinone-aomi neutron-linuxbridge-agent[15864]: Option "verbose" from group "DEFAULT" is deprecated for removal.  Its valu...uture.
Mar 01 16:24:06 allinone-aomi neutron-linuxbridge-agent[15864]: Option "notification_driver" from group "DEFAULT" is deprecated. Use optio...ions".
Mar 01 16:24:06 allinone-aomi sudo[15900]:  neutron : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/neutron-rootwrap-daemon /etc/neutro...rap.conf
Mar 01 16:24:07 allinone-aomi systemd[1]: neutron-linuxbridge-agent.service: main process exited, code=exited, status=1/FAILURE
Mar 01 16:24:07 allinone-aomi systemd[1]: Unit neutron-linuxbridge-agent.service entered failed state.
Mar 01 16:24:07 allinone-aomi systemd[1]: neutron-linuxbridge-agent.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@allinone-aomi ~]# tail -n23 /var/log/neutron/linuxbridge-agent.log 
2017-03-01 16:24:07.012 15864 ERROR neutron     (stderr,))
2017-03-01 16:24:07.012 15864 ERROR neutron Exception: Failed to spawn rootwrap process.
2017-03-01 16:24:07.012 15864 ERROR neutron stderr:
2017-03-01 16:24:07.012 15864 ERROR neutron Traceback (most recent call last):
2017-03-01 16:24:07.012 15864 ERROR neutron   File "/usr/bin/neutron-rootwrap-daemon", line 10, in <module>
2017-03-01 16:24:07.012 15864 ERROR neutron     sys.exit(daemon())
2017-03-01 16:24:07.012 15864 ERROR neutron   File "/usr/lib/python2.7/site-packages/oslo_rootwrap/cmd.py", line 57, in daemon
2017-03-01 16:24:07.012 15864 ERROR neutron     return main(run_daemon=True)
2017-03-01 16:24:07.012 15864 ERROR neutron   File "/usr/lib/python2.7/site-packages/oslo_rootwrap/cmd.py", line 98, in main
2017-03-01 16:24:07.012 15864 ERROR neutron     daemon_mod.daemon_start(config, filters)
2017-03-01 16:24:07.012 15864 ERROR neutron   File "/usr/lib/python2.7/site-packages/oslo_rootwrap/daemon.py", line 98, in daemon_start
2017-03-01 16:24:07.012 15864 ERROR neutron     server = manager.get_server()
2017-03-01 16:24:07.012 15864 ERROR neutron   File "/usr/lib64/python2.7/multiprocessing/managers.py", line 493, in get_server
2017-03-01 16:24:07.012 15864 ERROR neutron     self._authkey, self._serializer)
2017-03-01 16:24:07.012 15864 ERROR neutron   File "/usr/lib64/python2.7/multiprocessing/managers.py", line 162, in __init__
2017-03-01 16:24:07.012 15864 ERROR neutron     self.listener = Listener(address=address, backlog=16)
2017-03-01 16:24:07.012 15864 ERROR neutron   File "/usr/lib/python2.7/site-packages/oslo_rootwrap/jsonrpc.py", line 66, in __init__
2017-03-01 16:24:07.012 15864 ERROR neutron     self._socket.bind(address)
2017-03-01 16:24:07.012 15864 ERROR neutron   File "/usr/lib64/python2.7/socket.py", line 224, in meth
2017-03-01 16:24:07.012 15864 ERROR neutron     return getattr(self._sock,name)(*args)
2017-03-01 16:24:07.012 15864 ERROR neutron socket.error: [Errno 13] Permission denied
2017-03-01 16:24:07.012 15864 ERROR neutron 
2017-03-01 16:24:07.012 15864 ERROR neutron 
[root@allinone-aomi ~]# cat /var/log/audit/audit.log  | grep rootwrap
type=AVC msg=audit(1488385426.894:1938): avc:  denied  { create } for  pid=15813 comm="neutron-rootwra" name="rootwrap.sock" scontext=system_u:system_r:neutron_t:s0 tcontext=system_u:object_r:neutron_tmp_t:s0 tclass=sock_file
type=AVC msg=audit(1488385446.993:2879): avc:  denied  { create } for  pid=15901 comm="neutron-rootwra" name="rootwrap.sock" scontext=system_u:system_r:neutron_t:s0 tcontext=system_u:object_r:neutron_tmp_t:s0 tclass=sock_file
```

**Comment by abelboldu** [comment]
@ryo-tagami  I think it's because we're using outdated centos 7 images.
`semodule -i /usr/share/selinux/packages/os-neutron.pp.bz2` failed on a first run, but worked after a `yum update -y`
Then I could do a `systemctl status neutron-linuxbridge-agent`

**Comment by ryo-tagami** [comment]
retest this please

**Review by ryo-tagami — APPROVED** [review]

**Comment by ryo-tagami** [comment]
You're right, updated the VM image.

**Comment by abelboldu** [comment]
🙇 thanks

**Pull request merged**
